name:         Class-WeakSingleton
version:      1.03
license:      perl
version_from: WeakSingleton.pm
installdirs:  site
requires:
  Scalar::Util: 0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07

