---
name: Class-WeakSingleton
version: 1.04
author:
  - Joshua ben Jore <jjore@cpan.org>
abstract: A Singleton that expires when all the references to it expire
license: perl
requires:
  Scalar::Util: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Class::WeakSingleton:
    file: lib/Class/WeakSingleton.pm
    version: 1.04
generated_by: Module::Build version 0.2611
